# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- project:
    templates:
      - docs-on-readthedocs
    vars:
      rtd_webhook_id: '38809'
      rtd_project_name: 'airship-drydock'
    check:
      jobs:
        - openstack-tox-py312
        - airship-drydock-openstack-tox-cover-noble
        - airship-drydock-openstack-tox-pep8-noble
        - airship-drydock-baclient-test
        - airship-drydock-run-test
        - airship-drydock-integration-test
        - airship-drydock-chart-build-gate
        - airship-drydock-chart-build-latest-htk
        - airship-drydock-docker-build-gate-ubuntu_noble
        - drydock-airskiff-deployment-noble-kubeadm

    gate:
      jobs:
        - openstack-tox-py312
        - airship-drydock-openstack-tox-cover-noble
        - airship-drydock-openstack-tox-pep8-noble
        - airship-drydock-baclient-test
        - airship-drydock-run-test
        - airship-drydock-integration-test
        - airship-drydock-chart-build-gate
        - airship-drydock-docker-build-gate-ubuntu_noble

    post:
      jobs:
        - airship-drydock-docker-publish-ubuntu_noble
        - drydock-upload-git-mirror

- nodeset:
    name: airship-drydock-single-node-noble
    nodes:
      - name: primary
        label: ubuntu-noble

- nodeset:
    name: airship-drydock-single-node-jammy
    nodes:
      - name: primary
        label: ubuntu-jammy

- job:
    name: airship-drydock-openstack-tox-cover-noble
    parent: openstack-tox-cover
    description: Runs cover job on noble
    nodeset: airship-drydock-single-node-noble
    pre-run: tools/gate/playbooks/install-docker.yaml
    vars:
      tox_environment:
        DISTRO: ubuntu_noble

- job:
    name: airship-drydock-openstack-tox-pep8-noble
    parent: openstack-tox-pep8
    description: Runs pep8 job on noble
    nodeset: airship-drydock-single-node-noble
    pre-run: tools/gate/playbooks/install-docker.yaml

- job:
    name: airship-drydock-baclient-test
    description: |
      Run a bootaction drydock client test
    run: tools/gate/playbooks/baclient_test.yaml
    timeout: 3600
    nodeset: airship-drydock-single-node-noble
    pre-run: tools/gate/playbooks/install-docker.yaml

- job:
    name: airship-drydock-run-test
    description: |
      Run a bootaction drydock client test
    run: tools/gate/playbooks/run_drydock.yaml
    timeout: 3600
    nodeset: airship-drydock-single-node-noble
    pre-run: tools/gate/playbooks/install-docker.yaml
    vars:
      distro: ubuntu_noble

- job:
    name: airship-drydock-integration-test
    description: |
      Run a bootaction drydock client test
    run: tools/gate/playbooks/integration_test.yaml
    timeout: 3600
    nodeset: airship-drydock-single-node-noble
    pre-run: tools/gate/playbooks/install-docker.yaml
    vars:
      distro: ubuntu_noble

- job:
    name: airship-drydock-chart-build-gate
    description: |
      Builds charts using pinned Helm toolkit.
    timeout: 900
    run: tools/gate/playbooks/build-charts.yaml
    nodeset: airship-drydock-single-node-noble
    vars:
      HTK_COMMIT: 49c117443391cec75e0bd52bb4a9d033325927ad

- job:
    name: drydock-airskiff-deployment-noble-kubeadm
    # Pinned for now due to Ansible 11 stopped verbosive output.
    ansible-version: 9
    description: |
      Deploy drydock using Airskiff and submitted Shipyard changes.
    parent: treasuremap-airskiff-deploy-maas-drydock-base
    nodeset: treasuremap-airskiff-1node-32GB-ubuntu_noble
    required-projects:
      - name: airship/treasuremap
        override-checkout: v1.9
    roles:
      - zuul: airship/treasuremap
    vars:
      treasuremap_ref: v1.9
      CLONE_DRYDOCK: false
      MAKE_DRYDOCK_IMAGES: true
      MAKE_MAAS_IMAGES: false
      DOCKER_REGISTRY: localhost:5000
      gate_scripts_relative_path: ../../airship/treasuremap
      zuul_treasuremap_relative_path: ../../airship/treasuremap

- job:
    name: airship-drydock-chart-build-latest-htk
    description: |
      Builds charts using latest Helm toolkit.
    timeout: 900
    voting: false
    run: tools/gate/playbooks/build-charts.yaml
    nodeset: airship-drydock-single-node-noble
    vars:
      HTK_COMMIT: master

- job:
    name: airship-drydock-docker-build-gate-ubuntu_noble
    timeout: 3600
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: airship-drydock-single-node-noble
    irrelevant-files:
      - '^doc/.*'
      - '^charts/.*'
    vars:
      publish: false
      distro: ubuntu_noble
      tags:
        dynamic:
          patch_set: true



- job:
    name: airship-drydock-docker-publish-ubuntu_noble
    timeout: 3600
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: airship-drydock-single-node-noble
    secrets:
      - airship_drydock_quay_creds_2026
    irrelevant-files:
      - '^doc/.*'
      - '^charts/.*'
    vars:
      publish: true
      distro: ubuntu_noble
      tags:
        dynamic:
          branch: true
          commit: true
        static:
          - latest
          - airflow_3.1.5

- secret:
    name: airship_drydock_quay_creds_2026
    data:
      username: !encrypted/pkcs1-oaep
        - Krh7mBGG95zoz2q2ru/KwvHb00kpv/nuvqr6HYJ0MAdcPH3X+5ZCO29gv1kxZ/2VJabdL
          LfxorTKADEvGB49WK3PRb29PgBDZNJIM9OnWxvS34flCDKHi8qEMpsv/9RPHcxLTz7Tpy
          qBQ12QFdaeh9dp4iBKtor8SOCqyDcKb/+uC9yxhGvCRV8IQxIyV6oL21qL8Py3/nQgHMY
          B6AHjb5qDn8BXtCo3/o+Ax683til5o/83oX1tTtLBrIU2Gl15wJd9ZviyHEiniD7e5ZYB
          gnK+4TArhSWVAA+B8KeA+oewCJDH7Mtj4c3HAC9v2FfHGQtqhHGsTo4H3sojZGvv4ReoX
          GSbobRmMqF4fD3nFlC/I+EwTDTWQKmLD2lFtId2DCbsc52cbEOnktSeB8Av+N6vnBrETp
          1dzccLWb1wIhS07wep1HmI1xjPO5lFdzk4qleeEsa1XfUjX6yj9dGhJZZlEsjcuHA+ytn
          H9zU89d3Ibzq/EXKhOlo+Ls395vfeBO3I5iCSAEvIecpqQJDCgDN1EukqhuStcaMj4ikQ
          VNAe5r2sufUfh/yJslEs0f1PRRGRStIzXZX1R4TqJa1wqZTSLisV9GGb2xEUXi0kyPurS
          yGgRl/HzgAz1xqP9DTK92HcB8pvLfobooIL19UvBB9cctNQd/Zn+cnhLe76UNg=
      password: !encrypted/pkcs1-oaep
        - eSJXvZg2P3/T9Psvf+Q32CpAaiFTPTAY13I20rcxn3Aa1jApLkG2JIeXHwzKKHH5fH+1+
          09a6ctTbUsH7K1duZ8+5QYlHB/cKzV+rjjdmS1JM8eKFMH1vJhFsOHG0NRw1b1x6bEnda
          r3dgYDUUrZ1l861f8bVy5+W2OcHBvqFLE7If9JJfXvlNOGbHTitfkXgoEm9h/Pgn+P3rn
          HQeZjAXwWIWNveFBUW4Wt4YGv/kEg6KYU5dDI4HFaLjz0deTML5scOCp3kMIY1Yn8s8Fp
          TppE3Mo+/SohGfcbBX3jV8tUkZb0a6e5cuYgrNyn3X+INqDds/7brSTXOwhUPTUj47w1O
          ej80/HSd4KapM3sKdHprYzULepykzF4554QNkLNygL2knPjhRNOR7Nbf2re90qnZKePeW
          vWoHFJgfz1s7rGEVRha/KARF0cX38jDN0IlWYZchm5eaNEuRFYP8SdNPbmS5iworh7ZZH
          DcGjc8kolM8IL0eFGfUo8PcHAgqq0fKksifJKYeFv/XpfpbJlMn3r5FG3eBufw6WchEEy
          gdaHRUQeu+8LG3nd/Ok/A1BzuLrbRp+lR2tecoILzK6b/STAz8+o/p4m5MCCrnyEPiwVU
          7pl9LEfyjdY1dHhBevoo6L1gCzpt2sERQhNXrWnVREl6Mea3G9epoKKYjIEv8A=


- job:
    name: drydock-upload-git-mirror
    parent: upload-git-mirror
    description: Mirrors airship/drydock to airshipit/drydock
    vars:
      git_mirror_repository: airshipit/drydock
    secrets:
      - name: git_mirror_credentials
        secret: drydock-airshipit-github-ed25519-secret-2026-01-13
        pass-to-parent: true

- secret:
    name: drydock-airshipit-github-ed25519-secret-2026-01-13
    data:
      user: git
      host: github.com
      host_key: github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
      ssh_key: !encrypted/pkcs1-oaep
        - TdSQdGw/0LYVAIEQ5whmxRtpFFs11ID6kYXZNAKUtdZE6vgRYrlCYs5Eo4QzYUgChkbdt
          xIcRGmrreTFhtSLYAsf6VMaJ0Yr5C2fe0SCMlnAljVA1O6urWOfWQ9UEbyZVV21yysNeZ
          EHzvzoGjGwlwZrBMqn0AVdixQ1ZMsK1TzgPOAkTMpuuibrahiG5ZmjhZun4XHUl4EP5Pn
          u+HpT6vyDZY94ukdFddQEOtBY/hyjx4j7gLUz3ORx3f338AKYa3TkHv5la5H58aviB3vq
          kaUs2k7P/IYc6eRnVJYos7irCZ8UroKORpIy1hkq3afH/pcJKFfz0AwJtQRgmSLHJNj7w
          Z2NHLy1P7/PCkj0Xyf9+Iw1HgkSblE1MQ5P6NQkL7ZSJYz+38WC6hFQbvOkBY/6nms7K0
          JVCWuG1avDw+lBZ1ZywsPWAf7TzZbcJWXVr+sLul6TzRHmZ4SiHlMvWMuHtTnLpbNzy3q
          L/hjpw0Av1t8Uqtw9plbc89sL20AvllwQ0c8ucXPNPF2Y1ZD3QlozfHyRbvvjrpJB6p+R
          m7auA5EMOKRKjNkHdkkLTNLwzhSIF81QnKUVmibCryaBIgbpUiXstPZF81+wGDdLVhOQS
          fZt05oTNER9ZLd9hU/UmBqeLR++cpnmVtdTNS7pbolzuN+HKKpddva5XRbOLms=
