# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- project:
    check:
      jobs:
        - airship-drydock-omni-test
        - airship-drydock-chart-build-gate
        - airship-drydock-chart-build-latest-htk
        - airship-drydock-docker-build-gate

    gate:
      jobs:
        - airship-drydock-omni-test
        - airship-drydock-chart-build-gate
        - airship-drydock-docker-build-gate

    post:
      jobs:
        - airship-drydock-doc-publish
        - airship-drydock-docker-publish
        - drydock-upload-git-mirror

- nodeset:
    name: airship-drydock-single-node
    nodes:
      - name: primary
        label: ubuntu-xenial

- job:
    name: airship-drydock-omni-test
    description: |
      Run a set of lightweight lints and tests
      (pep8, Helm chart lint, Sphinx build, Python unit tests, Bandit scan)
    run: tools/gate/playbooks/omni_test.yaml
    timeout: 900
    nodeset: airship-drydock-single-node

- job:
    name: airship-drydock-chart-build-gate
    description: |
      Builds charts using pinned Helm toolkit.
    timeout: 900
    run: tools/gate/playbooks/build-charts.yaml
    nodeset: airship-drydock-single-node

- job:
    name: airship-drydock-chart-build-latest-htk
    description: |
      Builds charts using latest Helm toolkit.
    timeout: 900
    voting: false
    run: tools/gate/playbooks/build-charts.yaml
    nodeset: airship-drydock-single-node
    vars:
      HTK_COMMIT: master

- job:
    name: airship-drydock-docker-build-gate
    timeout: 1800
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: airship-drydock-single-node
    irrelevant-files:
      - '^docs/.*'
      - '^charts/.*'
    vars:
      publish: false
      tags:
        dynamic:
          patch_set: true

- job:
    name: airship-drydock-docker-publish
    timeout: 1800
    run: tools/gate/playbooks/docker-image-build.yaml
    nodeset: airship-drydock-single-node
    secrets:
      - airship_drydock_quay_creds
    irrelevant-files:
      - '^docs/.*'
      - '^charts/.*'
    vars:
      publish: true
      tags:
        dynamic:
          branch: true
          commit: true
        static:
          - latest

- job:
    name: airship-drydock-doc-publish
    description: |
      Publish documentation on airship-drydock.readthedocs.io
    run: tools/gate/playbooks/doc-publish.yaml
    secrets:
      - airship_drydock_readthedocs
    timeout: 300
    nodeset: airship-drydock-single-node

- secret:
    name: airship_drydock_quay_creds
    data:
      username: !encrypted/pkcs1-oaep
        - La6hrlZZdII5Vj994+Z1jULfO2/+fsbYjiF2PU5Cka9lsg7VksIPhuCXxSZVwLBoLphhb
          ErNe3kvoPB8Sx1VBhkua7OOEjYVZZjJziadxwZfuvTcrOInGAM7XdK7Bks17v4HaL1dyz
          6ccMuLrXJeE708ts8jaKMmyKaS8wb2A4KiBVLZQP89gS8EFvVSzxK3DWXHdAP7IezQyk4
          Fi4MsNnOSEJY45Fy+ibZ07bDxYEQHL6hpBhQYht1DUQkeqAiDSnShBMb1+G3HGk3SMjae
          PDGtL3fz4zixok+jU3BDbvPKoEFEz45AoQHILTL+KoPPQbRQOmrGXOh7nmEtGyFZar6be
          wy+rYisXdJVaoqCGPMRPkBSkohgl/80Ary1d0U+k9vlDnFjpw62svDJ1cuAoKXKOlUWgF
          qs6+GaN5ltnmYfakpgo4vrkbuXw2DdKAio3cDW+PA0O4aV9yCvDtbeFY2SfQX6WExxk25
          CIu0UbL/eB/lRrb3PMElJbF7RmRrX5mf4k11YhnslHATzGMzGkQ1VkZQH/C+Q2xx5XSGP
          ZFJCLNYvY/hF6IyrCx6lpsCThfRYxQd3jy1Du1qjv23mUnDueTzGvz7somBazB/ceom4z
          v0T98h7JHDZhfq/HiGyliRwCh4R7J/xxf4xjLScoBwfGDZp1gPcCMAQC8NtAE8=
      password: !encrypted/pkcs1-oaep
        - Ae8OFJse6u76Vw6p6LqWwgFOWTdb4ACZktK9mbhUA4GSSdEOUKbDoEyuo5I9qFPLHeLA8
          fK7RjUoC+gItAiWZjQQxrDoqeuqykHRLnjo2p+yd3hDTVmHXYkEw1jmMb0iP+DNNMl2qh
          3beL1C6fyzjFcer+sdg7xk3vVetbHP7b8iIh6b6A6Oau1V+wQOOLYsU7gSuzxQBEbyj0/
          IZFKjaedsahgPEE4XU2Qf9/aGe463u+OgJ+6tBj2I7GcDGqQlvAzDud+Z6Mbs2W1fjR9i
          026rE4k5UWVZAmz0ySh8zdR4aV46+rEBV4jXKimCD+P0DAfbusG0plQGqODlJGdQ2rikK
          4Gmu9XlG7j7Qm3GddPLLRkSfetn4oisI/zbKcPy1kz1tWQ3OqRmdxExJH5TiZMbo/7u4B
          7X6sKjrQvwSPRH8BDdwtS4iECsJvyO1pwWar4WfApBXo73RaaERzNcq3gLR64JFmc8IMF
          aknseZhtmaqM+ttv2bUL23uzYEkupY3foEUa3ILYs2qx5sofi6CBAOWd2c3t3d34Kn5ya
          B1qsfXoY9lVL59lCl4jYLqyGA99Oybi5YKTP8O+IH5Xo7XLOje7K0Vfvh7v8Mcja8pZRG
          sgRbPr/10a2g6+s37XofkFEeba7B8fV5h6v/A3tMy7U01rZ2qLBC/4hxrikXT8=

- secret:
    name: airship_drydock_readthedocs
    data:
      url: !encrypted/pkcs1-oaep
        - dcOaNb6+3zCSp8rlmaA8U/v8kxzsB9MPqmbfbFSoyCsXOAMvluYSitmF7XpYdZLOXPOvm
          +stE6m57dRBDlryymoLHVUxgeAkA/4YR1/78tF8vTLBDbWaLXVLTFBjx6jg17nS9X/UKs
          W+UtSA1rVmeoaF8jrxO+c0IJjhgRDchFyPa9s7CnrxUn12IN6IDym0YcUQLxUOFzofm3F
          fCtwFY84lRCJhB80jfXuYPlIdxTO3q245JlDvhRm4y6p/qCNljNm/Kw6o6ngKjh0f/CM6
          7oFZPsE1XDYWGvR0msq8rjCST6k380vIBeroOqfwRhrjU5YCTgZy2kmw/veY3eGs5bEbb
          OBZeIb6mk1+D9bmRbFaTmVns7E+a6Fdz/rrttebmak8aBATQD9sgBnvghFAAHibT4LNdn
          ic+eEy/RXqyHqZuIPukQjAF0FgfK7jDqVzB/scx2tpw7lYwpDZM8bOHFNIAC4zRVg66O2
          1HPo4egknU8MQRy1FwNm7A91AY2cKZSusfrQlND/vflK27/lxCdHoOYw8JVaGxe02Ac+n
          XapfJuj7tAkFF+jeaWamB5CMiC+4M3zsrReB2/kqbxGFXC0nQ9q9AbVg48zCZFxNTVMLj
          J5K79voMoMmFoP14trhneFDs1Ki8FOLU1fqU7KrBYrlixI4FJwJ6ljEM9C/OvU=
      token: !encrypted/pkcs1-oaep
        - i6Js243rxTsL0V1l5UWsJalCiRh3kYs54nBz0M9KKrE5YYdAYkD59jKSPncUeG7V+VTkr
          LuwGpI837r/oaYqD7g4ZZhsE/X+xSE1PSdtsSY3t5GZZAPdKG4oSLxl0buTd23JsS6cU4
          7IAh4Q28wtaIXg8fZ69KVkGm2f2nXPNKbUH/yPTjFW51yEXI55AClNKzv+mVKLd1PNdCN
          USQkmF4fvgFreQym+NkZrUh78YMQI1uNT1e7rhD/jxYCjhZGAEr0Clxiu8UmLIRvxHgc2
          2SM99xT8s0/dRudePkSz3zXSagwWvdat8bHqpGHJrakjZvePtGeZrdk20v7JQHt8T3XBp
          InfWRB8ad/gDvgpstXiag4EHsJ7tnFuwsFDh+KSYySBjtkbYqY8Rx8lQ5qW/Qgk96LagJ
          yzpin6EquBcnnPNTGTYLRF9jtowzbI8G9ItRRWdvkIQSlMQDxROI4bVEnfLHgRMbAKVjF
          1oSaiEzMwMHj356qYBS06pBBF3Dr/OCIZNiBy3UU8J6OJt2XchMgy9TVhsGkj+HE092d+
          mADSwkA5TpfWJCo8rqTDO8cCXIeiG8kBoxjph5m7YNWUcbuRDQdbga1FjV4lMe9bMyOo5
          AJ6O8hl3q7CJElLw6Z7p9vW2wHUf/xr242pZnk70DiMkyXxzJFLLqvRsWctTDc=

- job:
    name: drydock-upload-git-mirror
    parent: upload-git-mirror
    description: Mirrors airship/drydock to airshipit/drydock
    vars:
      git_mirror_repository: airshipit/drydock
    secrets:
      - name: git_mirror_credentials
        secret: drydock-airshipit-github-secret
        pass-to-parent: true

- secret:
    name: drydock-airshipit-github-secret
    data:
      user: git
      host: github.com
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      ssh_key: !encrypted/pkcs1-oaep
        - QhMLTtGvYN+GvEF28brcFNk3/2mXVea9ZoPU4SqUvqy+T/0kdpGZ8RZkZ9mr6Odsl/WJl
          K3n6ct6VYv0l6kCjSLYZd2BcNXTebFEYAAPAhpaUavltMiW1pv/U+1VV1e8Ry6YQWiGII
          NjlVKN5ZGlYpuE706QcS18JV/HvzkaMMNKnp2/Yi3pGc5jWJSN4zNgZ4OiLxuuhFvyCZm
          wFMsfv+XqS7nsTO7hE7goswLcJ6CY3pYXMoLmS4jI8Xkoc/wc8AKziIAqv2yXOHrmPdWY
          NHbuGUccTA85RuDq94gkW2cz5BvR6m/cLpdbQmV5W3G2+ZVFPJtKiikImLBW29x3M22fP
          iLHN4BALD2qgoMab1+Igt+gx2ESoYaeBX0hzt2VY1D3R+r5O7fTktwdPpxcUBEVxLa0du
          NoolrCYglWCaN1F9DOCYpl/fFf4MeMUtKPiiI4p6j2vNqUMLlOq+GquB8hj4G3a30pTrr
          fbXF3/L07HutQQ+Jvvxx03aIwZAfmn0QzOTo1KrPQVCyX+HWK5CjhpPOWPqQ8lEIBaXbk
          zplLDncJrG11W3qPmRHsDfYgu82zCVZ5bn62ur+N+wstdhEeCEaP8jPWZ9dvwWwCsBX04
          RAQ0BFEQUwVr+QCz1Xi2H9SOjr7T5pVkcq1IDxVIP+6HYFWOcWgRMNtU/E4Xb0=
        - RD+YHDgMbXP4fgFbRub0JJDx6HT1IoOMjZonAqA8eB8QNc6nXoKIPp7+uSTjhXO03VoKh
          JpPYbzAKIYVPsePvI0Zi6LG08/tdD5auLLChjHrTKvNH9i7QqrBY+11THoSbdE2GQU/vq
          /8kZ053rfauTEEbHavyOstgaVe4VzYrf5GCIPWd0RLAE7+lcLdfa/hAA1zgkPz0s35stA
          sUUxRSpM2xEV6QWmNu/e0Id1X7cyAm8+ReK7aQGrRI+OH7zmbk19/kHl6CQwu0CATlkYr
          cir2oUsZLqztzZkoye+lgvuIl0MhJfVuW9T2a08I8sTUFn+7iAhsQF141E1Kim9HdhLX6
          tGEhNlSXlis6yjDOo3VClfISyYlFLipvLHcfwaIoyctR2qMBM8QZ/vobefeGCNnfnvGvc
          EO9WFlGAE+Wi0XJ+aHfnjyx3Uj0DyeYpjeaT2Z3Zh+FjHvAxf4HR61aAHsLneTNdH3jnk
          xQfQdSsxRhMNh8G672CChmHIVr65mUnCICdzRLv0n9zg+zX34GA+LuQvpchEREb5iUsGo
          USbfFPjxFredplwzbMLJhHREJmazgBscH/P1Yxm3MWvI+ui2L/FPUtDkbPA9N49boyezl
          klY9EjdiPyz0Rojv5LKPS9dD1xsbS0tTfzhJeNmAWkSpXAWYB3aD5mtmF73uWg=
        - YuZrKg3gP0lx4RX2IN0b39fCHebg4mONsZgJpOzdOwBZJmBUmjh/Vg0G5Elqn+WB/OlJ4
          O+dXavtOQtiNDSz9ysHgwTqXs7uyokt3IFio3oRTqXJC0SRss/KdknGRebFCgOm6FPKLj
          +HIRGYOzUwD4dMkEKJ5Fgeq28rqDITyiG88w7YxY4ZTmhKISHJWg/jRGq2P0jOy/W/1gB
          febTyWdEbWrMNaDADM7oHgRN4r1RNerh/CXppgcxKSIlgfxyYx3kvJXc7Z+QGVgxuHVds
          Ykgv18IYTPniXS2mXvHGbfdbg1GJwoQbzMHjhyLyTUYTPPe3afK7pSvTZTP7j1qj0Ta6J
          kLRKQx7mWIDtmQcqhO1ZQr4HnZsoNnifjO8uVvHz+HM8fqFlCfa62zndpBE/XNkoymC9I
          mqTv74XzQvCujWEprZZzcZG3YbwC3Utcoy3RjsjBbwTWp7Fg7rXbXtLfTGERt1FPvHa8c
          Sv7DLwic1IvE8CZz3E4lYhPuCTpt+sOlxW24+MiyguRXn7SJrKnOCKHsyOUOs5cwhR35X
          0hVmp3Arlu37tQNDZA1juLtw4D3bWPDPdkQcuncnQEs4n2kzEJR0Vk8XKomhJgKzXhP+B
          zybYvKpX5F56i3bfSs8as8CWLvih4kcwwj9fZvZlBtlWkL2jHwkFVBj/kQUczc=
        - J8Rf3NwfzPpSUU+F4Q+DZL7D7HC8ILNmq0lnf5lPBUVuD0Aavf4GtZPTXtozj6CXFRQob
          xJg5eoYN39lTSGyuFrRa/WOGaP8kQiCYCXw2ZKAOt9+LuMn1/rLKMyzYQClFiZTQ7/dzP
          7kqcIqPjWgbqFviwKJ+wXTE3Ntp8qaECjaLFhcOBNJK1mCt1ciEJQo7a/R9nxvSS2PT1h
          LRnXHI5s5cY4Wzg1pEBt4l+GJ8qWI/3dI35pwM/vB5/Z/y+pJhwcR8gBD+ARjdELaM5M5
          rJAouss0w+OHOYI+IDpWxbHeTP633+TFLrIqK1fAm1z6NCl2e7uGEmWbGVnvROajyCJnd
          gLPSqm1Mt7rlGvIN60VipoXgcVRpfiubhr6DXNs1XGk18qVRgyWyQS6uHjefJOhhka5HK
          kYvWhoWVlA7O3+llRTzdQsSInppREKge78pHEk4lpGWBfwFX6snHB3y90Du4BcNIt3UKY
          EjON6sxnRPCkcekmpUGqD/IXFYV/qxdvfnoDdVW5M2SZWzsHdMoJdBhL53FFaYDyPxTaR
          4+kMmn8VTejOT2zQfny3zBoxMt30hYsAjHfDS62lxYJL/404uShhAi+1bpnyy+uxU39nQ
          v3QSn8NtjBdh/WKptpsma1yZEHKAJJjfU9pmSrFHBfvokOmvTygjIC2uxP0ppo=
